### ISSUE TITLE
2D modeling features and examples

### ISSUE THREAD

**Issue by lcheng9** [awslabs/palace#140]
*Description: A clear and concise description of what the feature is.*
I went through all examples, there are quite nice. My curiosity is any 2D feature or example available? I understand Palace is designed for 3D and large scale computing. Sometimes the user run the 2D models by first then move onto the more complicated 3D models. Thanks.

**Comment by Wangwei-Lan** [comment]
> * For 2D electrostatics problems, the solution to use Palace is to extrude your mesh 1 element in the normal-direction (the direction out of plane of the 2D mesh) and use that 3D mesh for the simulation. I believe the boundaries along the normal-direction should be "ZeroCharge" (the default if no BC is applied), indicating no electric field in the normal-direction and so this should work.

Hi, may I ask how to extrude mesh 1 element in the normal-direction as mentioned above? I was trying to test 2D problems and confused on how to solve it through palace. Thanks very much.

**Comment by sebastiangrimberg** [comment]
See this example from Gmsh: https://gmsh.info/doc/texinfo/gmsh.html#t3. You can generate a 2D mesh and use the `Extrude` functionality to extrude a fixed number of mesh layers to get a resulting 3D mesh. If not using Gmsh, this same type of functionality should be available in most mesh generation platforms to take a 2D mesh of triangles and generate a 2D mesh of prisms or tetrahedra.
