### ISSUE TITLE
Voltage boundary condition for the electrostatic analysis

### ISSUE THREAD

**Issue by lcheng9** [awslabs/palace#141]
*Description: A clear and concise description of what the bug is.*
Not a bug. 
When I looked into the example of **spheres**, the terminal boundary condition is used and no voltage value is assigned, while solution shows that one sphere surface has the voltage of 1. My questions are how a terminal boundary gives 1v to the surface, and how to impose other voltage values on the boundary, such as 5 v. Thank you.

**Comment by sebastiangrimberg** [comment]
We are always welcoming external contributions and pull requests to implement the particular cases you have in mind! We can provide some assistance in the development too, if you're stuck at any point.

**Comment by sebastiangrimberg** [comment]
I think this might be overcomplicating things. I guess the question to ask is: What types of quantities do you want to postprocess with this solution, where you have assigned different voltages to different terminals for a single solve? The reason to ask this is the following, and goes back to what I mentioned above. The model is linear, and thus if you just compute the solution for exciting terminal 1 (attribute 17) with 1V, and, separately, terminal 2 (attribute 25) with 1V, then the solution for exciting any combination of terminals 1 and 2 with voltages V1 and V2 is: V1 * u1 + V2 * u2, where u1 and u2 are the solutions from the 1V excitation above. This linear combination can be done in ParaView if you just want to visualize the results. If you want to do other postprocessing, then we can add this type of functionality to Palace with the specific postprocessing desires in mind. But either way this suggests a different interface than you have written above.

**Comment by sebastiangrimberg** [comment]
That's good that you are getting close to having a solution. Just to complete my understanding, I just wonder what are you trying to compute from the solution which you get? That is what I mean by "postprocessing". After you solve and get the voltage field (or electric field) from the excitation on the non-unit voltage BCs, what do you want to do with it?
