### ISSUE TITLE
PC freezes while building Palace

### ISSUE THREAD

**Issue by anadb** [awslabs/palace#161]
Hello,

I am trying to build palace manually. The installation goes well until it tries to compile mfem at around 98% my PC completele freezes. What is the reason of this behaviour?

My configuration is intel core 15-8400, 16 GB RAM, Manjaro 23.1.1

**Comment by sebastiangrimberg** [comment]
Hi @anadb, what command or commands are you using to configure and build the code? One thing that comes to mind is if you are using `make -j` with no number of processes specified, this can sometimes cause issues in my experience when too many parallel Make jobs are spawned. Specifying `-j16` instead should resolve this.

**Comment by anadb** [comment]
It works! Thank you very much indeed.
