### ISSUE TITLE
Support mesh boundary attributes by name instead of only index

### ISSUE THREAD

**Issue by nikosavola** [awslabs/palace#17]
*Description: A clear and concise description of what the feature is.*
Currently, mesh `Attributes` in the config JSON are arrays of integers corresponding to mesh attributes, could these optionally also support attribute names? For example, the spheres example mesh includes the following section
```gmsh
$PhysicalNames
4
2 2 "farfield"
2 3 "sphere_a"
2 4 "sphere_b"
3 1 "domain"
$EndPhysicalNames
```
Would be nice to be able to refer to the attributes as `farfield` etc.

For now one may easily write code to replaces the names by systematically, but I think this change would also make the JSON even more human-readable.

**Comment by sebastiangrimberg** [comment]
This is a good suggestion and I agree with you that is would be a nice feature for the JSON configuration file. Unfortunately this type of convenience is hard to achieve for the general set of mesh formats we aim to support (which is more than just Gmsh: see [MFEM's supported list](https://mfem.org/mesh-formats/) + native COMSOL and Nastran parsers). In many cases the format doesn't allow for general string names and only integers are available to tag element and boundary element attributes. Thus, while such a feature is certainly useful for Gmsh, I'm not sure how widely useful it would be for other mesh formats.

That said, I suppose one could build in support such that if the user specifies strings, we try to parse the mesh file and get the mapping from string names to integers when parsing the JSON configuration file and replace things internally. We could throw an error if the user specifies strings for a mesh type for which we don't know how to parse the string to integer mapping. Alternatively we could just leave it to the "client side" as you say where the user runs code to replace the names in their configuration file on their end before giving it to Palace.
