### ISSUE TITLE
Adaptive mesh refinement

### ISSUE THREAD

**Issue by sebastiangrimberg** [awslabs/palace#2]
Implement `solve-estimate-mark-refine` adaptive mesh refinement (AMR) process for all simulation types, as well as coarsening and load-balancing steps.

Use MFEM's functionality to support both conforming refinement for simplex meshes and nonconfirming refinement for meshes with hexahedra/prisms/pyramids. Requires AMR support for high-order H1, H(curl), and H(div) finite element spaces.

**Comment by hughcars** [comment]
Various ongoing work within MFEM to make this happen:
* https://github.com/mfem/mfem/pull/3611
* https://github.com/mfem/mfem/pull/3587
* https://github.com/mfem/mfem/pull/3541
