### ISSUE TITLE
MFEM abort error when trying to run simulation

### ISSUE THREAD

**Issue by andrekuo** [awslabs/palace#230]
I am getting the following error when trying to run a simulation using a .msh file generated using Qiskit Metal's QGmshRenderer.

![image](https://github.com/awslabs/palace/assets/50998428/bf7f3346-c937-4343-b8e5-7154b4b0b4b2)

I modified the default QGmshRenderer provided by Qiskit Metal to create a larger vacuum box (`sample_holder` in Qiskit Metal) around the metal+silicon substrate object. This was done to avoid overlapping in my .msh file: default QGmshRenderer creates a vacuum box that is exactly the size of the substrate and overlaps with the substrate sidewalls, thus creating overlapping mesh elements. Then, I export the design wireframe (without any meshing) into Gmsh, create a 3D mesh using Gmsh, and export as .msh from Gmsh. However, using this mesh file gives me the error shown above when trying to run an Eigenmode simulation with this .msh file. 
For reference, I am running PALACE locally on Windows 10, and I have attached both the config JSON and mesh file as a text file below:

[QGMSH_500um_thin_v1.json](https://github.com/awslabs/palace/files/14930908/QGMSH_500um_thin_v1.json)
[quarterwave_500um_thin.txt](https://github.com/awslabs/palace/files/14930920/quarterwave_500um_thin.txt)

Any thoughts on this would be greatly appreciated. I am positive that there is something wrong with the mesh file itself, rather than the config file, but I have exhausted all ideas for what could be wrong.

**Comment by sebastiangrimberg** [comment]
Hi @andrekuo, this is an error encountered during parsing of the mesh that almost certainly results from your mesh being invalid. Given the similarities, this might be related to the problems in https://github.com/awslabs/palace/issues/226, and even though you extended the outer domain boundary to get around the overlapping element issue you might still have an invalid mesh. I will take a look at your mesh file when I get a chance.

**Comment by sebastiangrimberg** [comment]
Hi @andrekuo, did you ever get a chance to make progress here? I am inclined to close the issue as mesh related but let me know if there is something else you'd like to investigate as a potential Palace issue.
