### ISSUE TITLE
Verification failed when solving a horn antenna using mesh file created by Gmsh. 

### ISSUE THREAD

**Issue by keheheke** [awslabs/palace#235]
i meet some problems when simulation a horn antenna by Gmsh and palace.I can't figure out if it's a problem with the mesh or the model.
The simulation model is composed of a copper horn antenna feeded by a waveport,and airbox outside as an Radiation boundary,see the attachment model.
The error is :
Verification failed: (lambda.real() > 1.0 / (1.0 - 1.0e-2)) is false:
 --> Computed wave port mode is or is very close to being evanescent

**Comment by sebastiangrimberg** [comment]
Hi @keheheke, thanks for sharing your mesh and input file. The first issue is with your model/mesh. The mesh on the wave port face does not conform to the horn boundary, you can see that the triangles discretizing the outer box lie on top of and intersect the triangles for the edge of the horn domain. This needs to be fixed in your CAD model.

![Screenshot 2024-04-22 at 8 38 50 AM](https://github.com/awslabs/palace/assets/26631700/37e1d732-b651-45c7-b96d-dcbd904e39b0)

Another note is that if you are applying PEC boundary conditions to the surface of the horn, you don't need to mesh the inside. However, it should not hurt to much in this case and so I imagine fixing the above mesh issue should allow your simulation to run.

Finally, I noticed that the version of Palace you are using from Weisim is quite outdated. You would be strongly recommended to use the `main` branch or most recent release, this includes bug fixes for wave ports specifically. This should build fine on WSL if you are using a Windows machine, or if you need access to a separate Linux machine you could use a public cloud provider like AWS.

**Comment by wlt8023** [comment]
> Hi @keheheke, thanks for sharing your mesh and input file. The first issue is with your model/mesh. The mesh on the wave port face does not conform to the horn boundary, you can see that the triangles discretizing the outer box lie on top of and intersect the triangles for the edge of the horn domain. This needs to be fixed in your CAD model. Unfortunately I don't have any examples of antennas for you, but you might be able to learn something from the CPW examples with wave ports [here](https://awslabs.github.io/palace/dev/examples/cpw/). One option is to use the OpenCASCADE kernel in Gmsh and use the `Fragment` operation in the API (I think this is `Coherence` or `BooleanFragment` in the .geo syntax) to ensure the boundary embedding is correct.
> 
> ![Screenshot 2024-04-22 at 8 38 50 AM](https://private-user-images.githubusercontent.com/26631700/324523262-37e1d732-b651-45c7-b96d-dcbd904e39b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjY0NjEsIm5iZiI6MTcxMzg2NjE2MSwicGF0aCI6Ii8yNjYzMTcwMC8zMjQ1MjMyNjItMzdlMWQ3MzItYjY1MS00NWM3LWI5NmQtZGNiZDkwNGUzOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZGVmMTEzYTNjNDRlYTFkZGVkY2VjYzQ1OThhOTg5YWJhYmFhZTAxODgzMTJhYTBkNjVlZjM4ZjY3YjIxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkbpY_LfRQeBeS0tJ18RBHkVSkQsqKiRd-oi65UFG7w)
> 
> Another note is that if you are applying PEC boundary conditions to the surface of the horn, you don't need to mesh the inside. However, it should not hurt to much in this case and so I imagine fixing the above mesh issue should allow your simulation to run.
> 
> Finally, I noticed that the version of Palace you are using from Weisim is quite outdated. You would be strongly recommended to use the `main` branch or most recent release, this includes bug fixes for wave ports specifically. This should build fine on WSL if you are using a Windows machine, or if you need access to a separate Linux machine you could use a public cloud provider like AWS.

Hello, do you have a tutorial on building Palace in Windows?

**Comment by keheheke** [comment]
> Hi @keheheke, thanks for sharing your mesh and input file. The first issue is with your model/mesh. The mesh on the wave port face does not conform to the horn boundary, you can see that the triangles discretizing the outer box lie on top of and intersect the triangles for the edge of the horn domain. This needs to be fixed in your CAD model. Unfortunately I don't have any examples of antennas for you, but you might be able to learn something from the CPW examples with wave ports [here](https://awslabs.github.io/palace/dev/examples/cpw/). One option is to use the OpenCASCADE kernel in Gmsh and use the `Fragment` operation in the API (I think this is `Coherence` or `BooleanFragment` in the .geo syntax) to ensure the boundary embedding is correct.
> 
> ![Screenshot 2024-04-22 at 8 38 50 AM](https://private-user-images.githubusercontent.com/26631700/324523262-37e1d732-b651-45c7-b96d-dcbd904e39b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzU2OTcsIm5iZiI6MTcxMzg3NTM5NywicGF0aCI6Ii8yNjYzMTcwMC8zMjQ1MjMyNjItMzdlMWQ3MzItYjY1MS00NWM3LWI5NmQtZGNiZDkwNGUzOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNDgxNDNkMTZiZDNhNjc2ODhhZDgzNmNkNWRkZGYyNzBlMDYyMmI1NmRmM2E5ZWFiMjFhYmM2ZjE1NDEwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q6tYTyWmfmPnW_lpXqvTubVW8HIl65WaHYvssXJKPDc)
> 
> Another note is that if you are applying PEC boundary conditions to the surface of the horn, you don't need to mesh the inside. However, it should not hurt to much in this case and so I imagine fixing the above mesh issue should allow your simulation to run.
> 
> Finally, I noticed that the version of Palace you are using from Weisim is quite outdated. You would be strongly recommended to use the `main` branch or most recent release, this includes bug fixes for wave ports specifically. This should build fine on WSL if you are using a Windows machine, or if you need access to a separate Linux machine you could use a public cloud provider like AWS.

thanks a lot, i fixed the geometry of my model by the 'Boolean Fragment'， then i can keep the mesh conform on the face and box, finally it can be solved.
 also, i used old version of palace integrated by Welsim at the windows system. i will keep learning and figure more about palace.

**Comment by sebastiangrimberg** [comment]
@keheheke Great to hear! I will close this issue now but feel free to reopen if you have further questions.

**Comment by keheheke** [comment]
@sebastiangrimberg 
hello,recently,I have a problem when using Palace to solve a Rectangle waveguide,  I want to get the Insertion loss(S21) . 
The cut off frequency of the  waveguide is 15GHz, 
if I set the start frequency <15GHz ,such as 10GHz, it will be error like the picture:

if I set the start frequency >15GHz ,such as 16GHz, the simulation will run successfully:

However, i need to get the S21 parameter at from 10GHz to 20GHz ,even the wave energy will be evanescent, is there any solution ？

**Comment by keheheke** [comment]
@sebastiangrimberg 
@sebastiangrimberg 

hello,recently,I have a problem when using Palace to solve a Rectangle waveguide, I want to get the Insertion loss(S21) .
The cut off frequency of the waveguide is 15GHz,
if I set the start frequency <15GHz ,such as 10GHz, it will be error like that:
<Verification failed: (lambda.real() > 1.0 / (1.0 - 1.0e-2)) is false:
 --> Computed wave port mode is or is very close to being evanescent (位 = (9.9999999973809139e-01,0.0000000000000000e+00))!>

if I set the start frequency >15GHz ,such as 16GHz, the simulation will run successfully:

However, i need to get the S21 parameter at from 10GHz to 20GHz ,even the wave energy will be evanescent, is there any solution ？

**Comment by sebastiangrimberg** [comment]
Hi @keheheke, thanks for your question. In general I'm not sure if it makes sense to try to drive a wave port below the cutoff frequency of the propagating mode, so I do not know what the expected result for S21 is in this case. However, there have been many recent improvements to wave ports which should at least allow your simulation to run below cutoff (< 15 GHz), even as recently as last week with #264. I would suggest as a place to start you build and run Palace from `main` instead of the outdated version it appears you are using. It appears to me that you are at least using the code from before https://github.com/awslabs/palace/pull/192 (merged Feb. 2024) which included some major upgrades to the wave port boundary mode solver.

**Comment by keheheke** [comment]
> Hi @keheheke, thanks for your question. In general I'm not sure if it makes sense to try to drive a wave port below the cutoff frequency of the propagating mode, so I do not know what the expected result for S21 is in this case. However, there have been many recent improvements to wave ports which should at least allow your simulation to run below cutoff (< 15 GHz), even as recently as last week with #264. I would suggest as a place to start you build and run Palace from `main` instead of the outdated version it appears you are using. It appears to me that you are at least using the code from before #192 (merged Feb. 2024) which included some major upgrades to the wave port boundary mode solver.

@sebastiangrimberg ,Thanks a lot,i will seek help to build the latest version for better features.
