### ISSUE TITLE
discontinuous Galerkin time domain method

### ISSUE THREAD

**Issue by wangjinchuan001** [awslabs/palace#277]
Hi I would like to know whether this software can use multi GPUs to accelerate the discontinuous Galerkin time domain i.e. DGTD method?

**Comment by hughcars** [comment]
Hi @wangjinchuan001, Palace does not use the Discontinuous Galerkin method so the immediate answer is no. Palace does however support GPUs, which is described in the [documentation](https://awslabs.github.io/palace/stable/guide/parallelism/), so I would recommend reviewing that as it may answer your questions.

**Comment by hughcars** [comment]
I'm going to close this, feel free to reopen if needed.
