### ISSUE TITLE
run example cpw

### ISSUE THREAD

**Issue by huangyb2** [awslabs/palace#284]
Missing "Probe" point "X", "Y", or "Z" in configuration file!
 ... in function: void palace::config::ProbePostData::SetUp(palace::config::json&)
 ... in file: /tmp/hyb/spack-stage/spack-stage-palace-0.12.0-vdycxrh7g4aclofgm5xnpw5pj4mz4k7x/spack-src/palace/utils/configfile.cpp:575

how to revise this error?
-->

**Comment by huangyb2** [comment]
I found the reason is json file mismatch with palace 0.12.

**Comment by hughcars** [comment]
Hi @huangyb2 I'm glad you managed to figure it out, the config files are still prone to some changes. We try to keep the changes to a minimum and to communicate them in the CHANGELOG.md file which should help.

**Comment by hughcars** [comment]
I'm going to close this ticket as it seems you have resolved the issue, feel free to reopen if you have other questions.

**Comment by VolkerMuehlhaus** [comment]
@huangyb2 How did you solve this? I am running into the same error with the example files.
