### ISSUE TITLE
Is direct solving method supported in palace?

### ISSUE THREAD

**Issue by yanfeit** [awslabs/palace#286]

**Comment by hughcars** [comment]
@yanfeit I am not sure what you mean by "direct" in this context, if you mean using a dense/direct linear solver, then no Palace does not support this as it is fundamentally built around iterative krylov methods. If you can clarify your question a bit I might be able to provide more of an answer.

**Comment by yanfeit** [comment]
> @yanfeit I am not sure what you mean by "direct" in this context, if you mean using a dense/direct linear solver, then no Palace does not support this as it is fundamentally built around iterative krylov methods. If you can clarify your question a bit I might be able to provide more of an answer.

Thank you for the kind reply. I was meant to ask whether Palace supports sparse matrix solver based on LU decomposition. I think you have already answered my question.

**Comment by hughcars** [comment]
> > @yanfeit I am not sure what you mean by "direct" in this context, if you mean using a dense/direct linear solver, then no Palace does not support this as it is fundamentally built around iterative krylov methods. If you can clarify your question a bit I might be able to provide more of an answer.
> 
> Thank you for the kind reply. I was meant to ask whether Palace supports sparse matrix solver based on LU decomposition. I think you have already answered my question.

Ah, we do make use of SuperLU and STRUMPACK (as seen [here in the docs](https://awslabs.github.io/palace/stable/config/solver/#solver[%22Linear%22])) as the coarse preconditioner in a multigrid hierarchy when doing frequency and time domain solves. However they are solving a real valued approximation of the complex system, thus are not directly solving the system. There is a [project we have planned](https://github.com/awslabs/palace/issues/142) to solve the complex system matrix itself, but that hasn't been attempted yet. Historically we have found the sparse direct solvers are very helpful for the coarsest solve in a multigrid hierarchy, as the system can be quite indeterminate and thus difficult for traditional preconditioning techniques.

**Comment by sebastiangrimberg** [comment]
Hi @yanfeit, sorry to chime in here but to add to Hugh's answer there is a keyword `"MGMaxLevels"` which you can set to `1` in your configuration file to disable multigrid and use a sparse direct solver on the assembled (potentially high-order) system. As Hugh says this is real-valued, but the GMRES solve should converge in very few iterations as it is typically a (provably) good preconditioner for the actual complex-valued system.

**Comment by yanfeit** [comment]
Hi @sebastiangrimberg , thanks for more clarifications and instructions. Since the answer has some technical details that I am not familiar with, I will discuss your answer with my colleagues.
