### ISSUE TITLE
How to setup the development environment?

### ISSUE THREAD

**Issue by LeSnow-Ye** [awslabs/palace#291]
Hello, Dev Team,

I've been trying to dive into the code, but I’m having some trouble setting up the development environment properly. While I can compile and run Palace without any issues, I failed to get rid of the red underlines in the editor.

I’m currently using VSCode with the following extensions:

- C/C++
- clangd
- CMake Tools
- Clang-Format

I also tried running `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..` to generate the `compile_commands.json` file. But somehow it seems no `compile_commands.json` file was generated.

I apologize if this is a bit *off-topic*, but I’m fairly new to C++, and any guidance would be greatly appreciated.

Thank you!

**Comment by hughcars** [comment]
Hi @LeSnow-Ye,

This is more of a vscode question than a Palace question. I can personally say I have had no issues developing Palace within vscode (ctrl click to go to definition works etc.) it's possible that you are not allowing the intellisense building to finish, or it is becoming bogged down in indexing build folders. I would suggest reading https://stackoverflow.com/questions/57458423/vs-code-not-recognizing-includes-from-includepath-during-build-intellisense-is and trying out some of that, and maybe checking your excluded files list in your vscode settings.

**Comment by LeSnow-Ye** [comment]
Thanks a lot. 
With only the official [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension by Microsoft (uninstalled `clangd` extension), I managed to get the environment fine.
