### ISSUE TITLE
Simulation patch antenna at single frequency point

### ISSUE THREAD

**Issue by huangyb2** [awslabs/palace#300]
Hi, If we could simulate antenna radiation problem only at single frequency point? Because i dont need wide-band response, and for the large electric problem, simulation at each frequency is time-consume.

**Comment by hughcars** [comment]
Hi @huangyb2,

If you are doing a frequency driven simulation, you can set the `"MinFreq"` and `"MaxFreq"` to the same value then only one frequency will be simulated. Namely `"MinFreq": 10` and `"MaxFreq": 10` would be a simulation just at `10GHz`.

Hugh

**Comment by huangyb2** [comment]
Hi@hughcars,
Thanks, It works!
