### ISSUE TITLE
Minor typo in the document examples/coaxial page

### ISSUE THREAD

**Issue by yanfeit** [awslabs/palace#303]
Dear developers of Palace team,

There is a minor typo in the document examples/coaxial page. I think it  will be helpful for further users to mitigate  their confusion. 

![image](https://github.com/user-attachments/assets/1cc738cd-563f-433a-bea2-2e5bec3875e2)

The  formula of Gaussion impulse has a wrong formula. The square should be on the \tau to be consistent with your implementation in the code.

![image](https://github.com/user-attachments/assets/03cd50c2-583f-4aa0-a039-98596d31d514)

Thanks,
Yanfei

**Comment by hughcars** [comment]
Hi @yanfeit thank you for the catch, you're right! The ^2 is outside the `{}` defining the denominator, fix https://github.com/awslabs/palace/pull/304
