### ISSUE TITLE
URL for magma needs updation

### ISSUE THREAD

**Issue by vegaonline** [awslabs/palace#313]

**Comment by hughcars** [comment]
HI @vegaonline, can you provide more details on the failure you're experiencing?

**Comment by vegaonline** [comment]
Hi @hughcars, While compiling I found errors for downloading magma. Then I found using `ccmake ..` that  the given URL (https://bitbucket.org/ic;/magma.git)  is not working. I found that https://bitbucket.org/icl shows that the magma repo has been moved to https:://github.com/icl-utk-edu/magma.  I thought it was a bug that might be corrected.

**Comment by hughcars** [comment]
Closing, was fixed in https://github.com/awslabs/palace/pull/316
