### ISSUE TITLE
An error occurs when using +Z ports in cpw example

### ISSUE THREAD

**Issue by WEIXUEP** [awslabs/palace#319]
Hi, while using +Z ports in cpw example, i encountered an error. The lumped ports are usually in +Z direction when constructing a circuit-level FEM simulation, so i modify the raw code of "cpw example": 
1. I set five surfaces of the model as "Absorbing Boundaries", and the bottom of the model is set as "PEC" (acting as GND).
2. The substrate is directly placed on the bottom "PEC Boundary".
3. I use the lumped ports in +Z, the width of the port is equal to the signal line.

**The height of the port should be equal to the substrate, however, under this condition, an error occurs:**
_Verification failed: (std::abs(l - mesh::GetProjectedLength(mesh, attr_marker, true, input_dir)) < rel_tol * l) is false:
 --> Bounding box discovered length should match projected length!
 ... in function: palace::UniformElementData::UniformElementData(const std::array<double, 3>&, const mfem::Array<int>&, const mfem::ParMesh&)
 ... in file: [palace/palace/fem/lumpedelement.cpp:60](/palace/palace/fem/lumpedelement.cpp:60)_

I try to set the height of the lumped port a bit larger than the substrate (for example, 1um, set "z_port_shift = 1" in the mesh generation code), it runs success. But it will spend more time on calculation, and the results are quite different.

Mesh generation code:
[mesh_myshape _lumped_GND3.jl.zip](https://github.com/user-attachments/files/18194515/mesh_myshape._lumped_GND3.jl.zip)
json file:
[cpw_lumped_uniform_zport.json](https://github.com/user-attachments/files/18194522/cpw_lumped_uniform_zport.json)
ipynb file:
[cpw_v2.ipynb.tar.gz](https://github.com/user-attachments/files/18194558/cpw_v2.ipynb.tar.gz)

```[tasklist]
### Tasks
```

**Comment by WEIXUEP** [comment]
I have done some other tests. I use the example in issue https://github.com/awslabs/palace/issues/282, this is a stripline example, also using lumped ports in +Z. However, the same error occurs:

_Verification failed: (std::abs(l - mesh::GetProjectedLength(mesh, attr_marker, true, input_dir)) < rel_tol * l) is false:
 --> Bounding box discovered length should match projected length!
 ... in function: palace::UniformElementData::UniformElementData(const std::array<double, 3>&, const mfem::Array<int>&, const mfem::ParMesh&)
 ... in file: [/home/10350374/10350374/wxp_codeSpace/palace/palace/fem/lumpedelement.cpp:60](https://file+.vscode-resource.vscode-cdn.net/home/10350374/10350374/wxp_codeSpace/palace/palace/fem/lumpedelement.cpp:60)_

_Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0_

**Comment by hughcars** [comment]
Calling palace with your model, it looks like a tolerancing issue. In particular adding some extra printing:
```
Verification failed: (std::abs(l - mesh::GetProjectedLength(mesh, attr_marker, true, input_dir)) < rel_tol * l) is false:
 --> Bounding box discovered length should match projected length: (1.1111111111111112e-01, 1.1111378538825967e-01, tol = 1.1111111111111111e-07!
 ... in function: palace::UniformElementData::UniformElementData(const std::array<double, 3> &, const mfem::Array<int> &, const mfem::ParMesh &)
 ... in file: /Users/hughcars/AWS/palace/palace/fem/lumpedelement.cpp:62
 ```

The issue can be traced back to the mesh cracking though I believe. If I run with `"CrackInternalBoundaryElements": false` on your case, then it passes just fine. The issue I believe comes from the vertices being slightly perturbed. I'll open an issue for this, but if you want to circumvent it for now, set `"CrackInternalBoundaryElements": false`  in the `"Model"` entry of the config file.

**Comment by WEIXUEP** [comment]
Thank you for your response. The issue has been successfully resolved based on your suggestion.

> Calling palace with your model, it looks like a tolerancing issue. In particular adding some extra printing:
> 
> ```
> Verification failed: (std::abs(l - mesh::GetProjectedLength(mesh, attr_marker, true, input_dir)) < rel_tol * l) is false:
>  --> Bounding box discovered length should match projected length: (1.1111111111111112e-01, 1.1111378538825967e-01, tol = 1.1111111111111111e-07!
>  ... in function: palace::UniformElementData::UniformElementData(const std::array<double, 3> &, const mfem::Array<int> &, const mfem::ParMesh &)
>  ... in file: /Users/hughcars/AWS/palace/palace/fem/lumpedelement.cpp:62
> ```
> 
> The issue can be traced back to the mesh cracking though I believe. If I run with `"CrackInternalBoundaryElements": false` on your case, then it passes just fine. The issue I believe comes from the vertices being slightly perturbed. I'll try and figure out a way to address this, but if you want to circumvent it for now, set `"CrackDisplacementFactor" : 0.0`, this is the perturbation of the mesh applied at any cracks, which defaults to `1e-3`, which is normally ok but for you is too large.
