### ISSUE TITLE
Any plan to support DG method or MoM/BEM?

### ISSUE THREAD

**Issue by EMinsight** [awslabs/palace#80]
Wow, this is a great project and similar to COMSOL.

Is there any plan for other CEM methods such as MoM/BEM, DG, Spectral, and so on?

**Comment by sebastiangrimberg** [comment]
Hi @EMinsight, thank you! We are happy to hear your positive feedback on Palace.

Palace aims to address a wide variety of CEM applications in terms of physical formulation (statics, frequency domain, time domain, etc.), but approaches all of them with a high-order finite element discretization. This is a general approach from a modeling point of view and and our goal is to handle problems which are also suitable for MoM/BEM codes with similar or better performance. In our experience we can get better performance with Palace than some MoM codes, though this obviously depends on the problem size and there are certainly places where the workflows associated with these methods are substantially simpler. So, it is probably not the goal long term to add MoM or BEM solvers to Palace but instead to improve the FE implementation enough such that they are not needed.

Regarding DG, there are many similarities between DG methods for Maxwell's equations and the finite element formulation on which Palace is built. Here there are sufficient differences in the numerical methods and their implementation that different implementations of different formulations may rank differently in terms of performance. Again, in Palace it is the goal to handle the same types of problems that DG CEM codes deal with, with our FE discretization. So probably there is not a need for implementing a DG method in Palace.

Lastly, regarding spectral elements, depending on the nomenclature you may just be referring to what we call "high-order" in the finite element formulation. In this case the answer would be that we already have it, and this is one of the key capabilities of Palace and the MFEM library on which it is build. Work in ongoing to implement efficient data structures for high-order finite elements to achieve substantial performance gains on CPUs and eventually GPUs. If you were instead referring to "global" spectral methods, this is different enough and probably out of scope for Palace.

I hope this helps! Please let me know if there are any points I can clarify further or if you have any opinions or thoughts on our outlook.

**Comment by EMinsight** [comment]
Thanks for your detailed answer.
